### ISSUE TITLE
Opt-in setting for requiring special capitation tool

### ISSUE THREAD

**Issue by tacotexmex** [HybridDog/treecapitator#9]
I really like treecapitator but for some games it allows for too fast progression. How about an optional global settings variable that registers a saw for example, that is required to trigger the capitation? Regular axes would function as in the default game.

**Comment by HybridDog** [comment]
Mods can override treecapitator.capitate_tree(pos, digger).
This mod shouldn't register saws in my opinion, but a setting which makes capitation only work with axes could be added.
And the technic mod adds a chainsaw which imo works worse than treecapitator, it could be changed to use treecapitator only if the trunk was dug with the technic chainsaw.

**Comment by tacotexmex** [comment]
Yes, if it requires a certain tool it's easy to override what tool that is from another mod.

**Comment by HybridDog** [comment]
https://github.com/HybridDog/treecapitator/commit/fbffeff665cf0fc785723b6c0f1b8c177a528ec3

**Comment by tacotexmex** [comment]
Great! Thank you @HybridDog. Now I can start hacking on my two man saw project. 😃

**Comment by tacotexmex** [comment]
Or can I? I don't get how to not only reduce capitation to when using proper tools but also to a specific tool only. Do you have it in your heart to provide an example?

**Comment by HybridDog** [comment]
```
function treecapitator.capitation_allowed(pos, digger)
	return digger:get_wielded_item():get_name() == "mod:some_tool"
end
```

**Comment by tacotexmex** [comment]
Thank you, I really appreciate it.
